name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Chceckout code
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-debug-
      - name: Build project
        run: cargo build --verbose --all --all-targets
      - name: Run tests
        env:
          AOC_SESSION: ${{secrets.AOC_SESSION}}
        run: cargo test --verbose
      - name: Run linter
        run: cargo clippy -- -D warnings
